/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import WebService.MessageThread;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dilum De Siva
 */
public class messageThreadPanelGenerator extends javax.swing.JPanel {

    DefaultListModel<MessageThread> listModel;
    Thread t;

    /**
     * Creates new form MessageThreads
     */
    public messageThreadPanelGenerator() {
        initComponents();
        Main.BlaBlaClient.allThreads = (ArrayList) getMessages(Main.BlaBlaClient.currentUser);
        fullList();
        t = new Thread(new Update());
        t.setDaemon(true);
        t.start();
    }

    private void addElements(DefaultListModel<MessageThread> listModel, ArrayList<MessageThread> thread) {
        for (MessageThread t : thread) {
            if (!listModel.contains(t)) {
                listModel.addElement(t);
            }
        }
        ThreadList.setModel(listModel);
        ThreadList.setCellRenderer(new threadViewGenerator());
    }

    public void fullList() {
        
        ArrayList<MessageThread> thread = (ArrayList) getMessages(Main.BlaBlaClient.currentUser);
        listModel = new DefaultListModel<>();
        addElements(listModel, thread);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ThreadList = new javax.swing.JList<>();
        lblWelcomeMsg = new javax.swing.JLabel();
        btnAddThread = new javax.swing.JButton();

        setBackground(new java.awt.Color(13, 127, 137));
        setMaximumSize(new java.awt.Dimension(800, 548));
        setMinimumSize(new java.awt.Dimension(800, 548));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(450, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(450, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 140));

        ThreadList.setBackground(new java.awt.Color(13, 127, 137));
        ThreadList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThreadListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ThreadList);

        lblWelcomeMsg.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblWelcomeMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMsg.setText("Welcome to Bla Bla");

        btnAddThread.setForeground(new java.awt.Color(13, 127, 137));
        btnAddThread.setText("Add Thread");
        btnAddThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddThreadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddThread)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(lblWelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblWelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAddThread, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddThreadActionPerformed
        // TODO add your handling code here:
        Main.BlaBlaClient.changeWindow(new threadPanelGenerator(), t);
    }//GEN-LAST:event_btnAddThreadActionPerformed

    private void ThreadListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreadListMouseClicked
        // TODO add your handling code here:
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            System.out.println("index: " + index);
            MessageThread thread = listModel.get(index);
            Main.BlaBlaClient.changeWindow(new messagesPanelGenerator(thread), t);
        }
    }//GEN-LAST:event_ThreadListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<WebService.MessageThread> ThreadList;
    private javax.swing.JButton btnAddThread;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcomeMsg;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<WebService.MessageThread> getMessages(WebService.User user) {
        WebService.ChatService_Service service = new WebService.ChatService_Service();
        WebService.ChatService port = service.getChatServicePort();
        return port.getMessages(user);
    }

    private class Update implements Runnable {
        @Override
        public void run() {
            while (true) {
                fullList();
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(messageThreadPanelGenerator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
}
