/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.xml.datatype.XMLGregorianCalendar;
import WebService.Message;

/**
 *
 * @author Dilum De Siva
 */
public class MessageViewGenerator extends javax.swing.JPanel implements ListCellRenderer<Message> {

    /**
     * Creates new form MessageView
     */
    public MessageViewGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMsg = new javax.swing.JLabel();
        lblSentTime = new javax.swing.JLabel();
        lblSender = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 77, 84));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblMsg.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblMsg.setText("Hi How Are You ?");

        lblSentTime.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblSentTime.setForeground(new java.awt.Color(255, 255, 255));
        lblSentTime.setText("12:02  2017.2.12");

        lblSender.setForeground(new java.awt.Color(255, 255, 255));
        lblSender.setText("Dilum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSentTime)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSentTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblSender;
    private javax.swing.JLabel lblSentTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Message> list, Message value, int index, boolean isSelected, boolean cellHasFocus) {
       lblMsg.setText(value.getMsgBody());
        lblSender.setText(value.getOwner().getUsername());
        XMLGregorianCalendar date = value.getRecievedDate();
        String time = "" + date.getHour() + ":" +date.getMinute() + " " + date.getYear()+"/"+date.getMonth() +"/"+ date.getDay();
        lblSentTime.setText(time);
        return this;
    }
}
