/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.xml.datatype.XMLGregorianCalendar;
import WebService.MessageThread;

/**
 *
 * @author Dilum De Siva
 */

public class threadViewGenerator extends javax.swing.JPanel implements ListCellRenderer<MessageThread> {

    int threadID;
    MessageThread messageThread;
    
    /**
     * Creates new form ThreadView
     */
    
    public threadViewGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_content = new javax.swing.JPanel();
        lblThreadTittle = new javax.swing.JLabel();
        lblEditedByShow = new javax.swing.JLabel();
        lblEditedBy = new javax.swing.JLabel();
        lblLastEdit = new javax.swing.JLabel();
        lblLastEditShow = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 77, 84));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        setMaximumSize(new java.awt.Dimension(450, 100));
        setMinimumSize(new java.awt.Dimension(450, 100));
        setPreferredSize(new java.awt.Dimension(450, 100));

        panel_content.setBackground(new java.awt.Color(7, 77, 84));
        panel_content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_contentMouseClicked(evt);
            }
        });

        lblThreadTittle.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        lblThreadTittle.setForeground(new java.awt.Color(255, 255, 255));
        lblThreadTittle.setText("Thread Tittle");

        lblEditedByShow.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblEditedByShow.setForeground(new java.awt.Color(255, 255, 255));
        lblEditedByShow.setText("Edited By :");

        lblEditedBy.setForeground(new java.awt.Color(255, 255, 255));
        lblEditedBy.setText("Dilum");

        lblLastEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblLastEdit.setText("2017/10/4");

        lblLastEditShow.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblLastEditShow.setForeground(new java.awt.Color(255, 255, 255));
        lblLastEditShow.setText("Last Edit :");

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addComponent(lblThreadTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addComponent(lblLastEditShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLastEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEditedByShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEditedBy, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addGap(85, 85, 85))))
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThreadTittle)
                .addGap(18, 18, 18)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditedByShow)
                    .addComponent(lblEditedBy)
                    .addComponent(lblLastEdit)
                    .addComponent(lblLastEditShow))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panel_contentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_contentMouseClicked

        
    }//GEN-LAST:event_panel_contentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEditedBy;
    private javax.swing.JLabel lblEditedByShow;
    private javax.swing.JLabel lblLastEdit;
    private javax.swing.JLabel lblLastEditShow;
    private javax.swing.JLabel lblThreadTittle;
    private javax.swing.JPanel panel_content;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends MessageThread> list, MessageThread value, int index, boolean isSelected, boolean cellHasFocus) {
        this.messageThread = value;
        lblThreadTittle.setText(value.getThreadName());
        lblEditedBy.setText(value.getThreadOwner().getUsername());
        XMLGregorianCalendar date = value.getThreadLastEdit();
        String lastEdited = ""+date.getYear()+ "/" + date.getMonth() +"/" +date.getDay();
        lblLastEdit.setText(lastEdited);
        this.threadID = value.getThreadId();
        return this;
    }
}
